#!/bin/bash
# Groundtruth Phase1 — autonomous launcher
#
# Generated by `parallel-start` (scripts/parallel/init-worktree.sh).
# Launches Claude Code in headless mode in this worktree to execute the plan.
#
# Permissions: --dangerously-skip-permissions is used. Bounded by:
#   - this worktree (reversible: `git worktree remove`)
#   - this branch (chore/groundtruth-phase1, requires PR + human merge to reach develop)
#   - per-PR review checkpoints
#
# Usage:
#   ./launch.sh             # start fresh
#   ./launch.sh --resume    # resume after rate limit / interruption
#
# Kill: Ctrl+C in the running terminal, or `pkill -f 'claude.*groundtruth-phase1'`.

set -e

WORKTREE="/Users/derekb137/src/github/groundtruth-groundtruth-phase1"
PLAN=".claude/plans/plan.md"
ADD_DIRS=""  # space-separated extra working dirs (e.g., deploy repo)

cd "$WORKTREE"

# Verify branch
BRANCH=$(git branch --show-current)
EXPECTED="chore/groundtruth-phase1"
if [ "$BRANCH" != "$EXPECTED" ]; then
    echo "ERROR: expected branch $EXPECTED, got $BRANCH"
    exit 1
fi

# Verify plan exists + has been filled out
if [ ! -f "$PLAN" ]; then
    echo "ERROR: plan not found at $PLAN"
    exit 1
fi
if grep -q '_Replace with task title_' "$PLAN"; then
    echo "ERROR: plan still has template placeholders. Fill out tasks before launching."
    exit 1
fi

# Initial prompt depends on mode
if [ "$1" = "--resume" ]; then
    INITIAL_PROMPT="Resuming groundtruth-phase1 execution. Read .claude/plans/state.json for current wave + in-flight tasks. Continue where you left off. Behaviors per .claude/plans/plan.md §6."
else
    INITIAL_PROMPT="Begin groundtruth-phase1 execution. Read .claude/plans/plan.md end-to-end first. Then execute Wave 1 in parallel via sub-worktrees per scripts/parallel/spawn-wave.sh. After Wave 1 verification gates pass, open PR per the plan, then proceed to Wave 2 without check-in. No pauses for permission prompts (this session is launched with --dangerously-skip-permissions). Update .claude/plans/progress.md after every task. Update .claude/plans/state.json with current wave + status. Hard-stop conditions in plan §6."
fi

# System prompt: autonomous mode reminder + key constraints
SYSTEM_APPEND=$(cat <<'EOF'
AUTONOMOUS_MODE=true. You are the orchestrator for this effort. Behaviors:
- Do NOT pause for user check-ins between waves or tasks.
- Do NOT ask permission to run shell commands; the session is launched with
  --dangerously-skip-permissions.
- Spawn sub-worktrees for parallel task execution within a wave (use
  scripts/parallel/spawn-wave.sh).
- Use sonnet for mechanical tasks; opus for design-heavy / high-risk ones
  (per task table in plan.md).
- After every task: run scripts/parallel/verify-gate.sh. If it fails,
  retry up to 2 more times with tighter spec. After 3 failures, mark BLOCKED
  in progress.md and move on to non-dependent tasks.
- After every wave: cherry-pick task commits via scripts/parallel/cherry-pick-wave.sh,
  run verification, open the PR (do NOT merge), update progress doc, proceed to next wave.
- On rate limit: write state to state.json, ScheduleWakeup in 1800s, resume cleanly.
- Read .claude/plans/USER_NOTES.md before starting each new wave for any
  user-injected feedback.
- Auto-push every commit (the post-commit hook in each sub-worktree handles this).
EOF
)

# Build --add-dir flags from ADD_DIRS
ADD_DIR_FLAGS=""
for d in $ADD_DIRS; do
    ADD_DIR_FLAGS="$ADD_DIR_FLAGS --add-dir $d"
done

echo "==================================================="
echo "Groundtruth Phase1 — autonomous launcher"
echo "==================================================="
echo "Worktree:       $WORKTREE"
echo "Branch:         chore/groundtruth-phase1"
echo "Base:           origin/develop @ 8168310cd"
echo "Plan:           $PLAN"
echo "Mode:           $([ "$1" = "--resume" ] && echo "RESUME" || echo "FRESH START")"
echo "Permissions:    --dangerously-skip-permissions (bypassed)"
echo "Extra dirs:     ${ADD_DIRS:-none}"
echo "==================================================="
echo ""
echo "Starting in 3 seconds. Ctrl+C to abort."
sleep 3

exec claude \
    --dangerously-skip-permissions \
    $ADD_DIR_FLAGS \
    --append-system-prompt "$SYSTEM_APPEND" \
    --model opus \
    "$INITIAL_PROMPT"
